version: '3'

services:
  backend:
    build:
      context: ./backend             # Path to the backend directory
      dockerfile: Dockerfile          # Dockerfile in the backend directory
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend             # Path to the frontend directory
      dockerfile: Dockerfile          # Dockerfile in the frontend directory
    ports:
      - "80:80"
