version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"       # Map NGINX port 80 to host port 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"     # Map Flask port to host
    environment:
      FLASK_APP: app.py  # Specify the main Flask file
      FLASK_RUN_HOST: 0.0.0.0
