name: Node.js CI

on:
  push:
    branches:
      - main
      - feature/CI_CD
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm ci

      - name: Run build (frontend)
        working-directory: ./frontend
        run: npm run build

      - name: Run tests (frontend)
        working-directory: ./frontend
        run: npm test

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh-keyscan -H 34.32.16.145 >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          ssh hailyqt@34.32.16.145 'cd ~/62582_DevOps && git pull && npm install && npm run start'
